version: '3.8'

services:
  smore:
    build: .
    container_name: smore-bitcoin-brute-force
    volumes:
      - ./smore/logs:/app/smore/logs
      - ./data:/app/data
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XAUTHORITY:-~/.Xauthority}:/home/appuser/.Xauthority
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    network_mode: "host"
    # Uncomment below section if running on Windows with XServer solution like VcXsrv
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    # environment:
    #   - DISPLAY=host.docker.internal:0.0 